/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.*;
import static mainpackage.CheckConnection.url;

/**
 *
 * @author konst
 */
public class newspaperEditing extends javax.swing.JFrame {

    /**
     * Creates new form newspaperEditing
     */
    public newspaperEditing() {
        initComponents();
        FillComboNewspaper();
        FillComboOwner();
        
        try{
      
	Connection con = DriverManager.getConnection(url);
	String sql ="SELECT * FROM article";
        Statement stmt;
        ResultSet rs;
        stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        rs = stmt.executeQuery(sql);
       
        }
        
        catch(SQLException ex){
            Logger.getLogger(submitArticle.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        newspaperCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ownerCombo = new javax.swing.JComboBox<>();
        frequencyCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please enter the newspaper you want to edit :");

        jButton1.setText("Confirm Changes");

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Publication Frequency:");

        jLabel4.setText("Owner's name:");

        ownerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerComboActionPerformed(evt);
            }
        });

        frequencyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly", "Monthly" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(102, 102, 102)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newspaperCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ownerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(frequencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(newspaperCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(frequencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void FillComboOwner()
    {
	try
	{
	    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	    //String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SELECT publisher_email FROM publisher";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("publisher_email");
		ownerCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void FillComboNewspaper()
    {
	try
	{
	    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	    //String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
            
	    String sql = "SELECT newspaper_name FROM newspaper INNER JOIN publisher ON newspaper.owner_email = publisher_email";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("newspaper_name");
		newspaperCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  

    
     private void InsertTextIntoDB()
     {
         try
	{
	    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	    //String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "UPDATE newspaper SET publication_frequency=' ";
            Object varName1 = (Object)frequencyCombo.getSelectedItem();
            Object varName2 = (Object)newspaperCombo.getSelectedItem();
            String value1 = frequencyCombo.getSelectedItem().toString();
            String value2 = newspaperCombo.getSelectedItem().toString(); 
            String sql1 = sql.concat(value1);   // Combining Initial query with the text from comboBox
	    String sql2 =" WHERE newspaper_name ='";                //  Adding the final elements of the query
	    String sql3 = sql1.concat(sql2); //
            String sql4 = sql3.concat(value2);
            String sql5 = "';";
            String sql6 = sql4.concat(sql5);
            PreparedStatement pst = con.prepareStatement(sql6);
	    ResultSet rs = pst.executeQuery();
            con.close();
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
     }
     
     private void ChangeOwnerActionPerformed(java.awt.event.ActionEvent evt)                                              
    {                                                  
        try
	{
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SET NOCOUNT ON UPDATE newspaper SET owner_name='"; //Initial SQL query to update a column
	    Object varName = (Object)newspaperCombo.getSelectedItem(); //Get the text from the ComboBox
            Object varName2 = (Object)ownerCombo.getSelectedItem();
            String value1 = ownerCombo.getSelectedItem().toString();
	    String value2 = newspaperCombo.getSelectedItem().toString(); // And pass it to a string.
	    String sql1 = sql.concat(value1);   // Combining Initial query with the text from comboBox
	    String sql2 =" '";                //  Adding the final elements of the query
            String sql3 = sql1.concat(sql2);
            String sql4 = " WHERE newspaper_name ='";
	    String sql5 = sql3.concat(sql4); //
	    //System.out.println(sql3); //Troubleshooting print to eastablish if concat is working as intended
	    PreparedStatement pst = con.prepareStatement(sql5);
	    ResultSet rs = pst.executeQuery();
	    con.close();
	}
	catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
    }                                             
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.hide();
       publisher pb = new publisher();
       pb.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ownerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newspaperEditing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newspaperEditing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newspaperEditing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newspaperEditing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newspaperEditing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> frequencyCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> newspaperCombo;
    private javax.swing.JComboBox<String> ownerCombo;
    // End of variables declaration//GEN-END:variables
}
