/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
*/
package mainpackage;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.*;
//import net.proteanit.sql.DbUtils;
import static mainpackage.CheckConnection.url;


/**
 *
 * @author Vasilis
 */
public class submitArticle extends javax.swing.JFrame
{
     public submitArticle()
    {
	initComponents();
	FillComboPath();
        FillComboTitle();
        FillComboPages();
        FillComboSummary();
        FillComboKeyWords();
        FillComboAuthor();
        FillComboCategory();
        FillComboPageNum();
        
        try{
      //  Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
        //String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	Connection con = DriverManager.getConnection(url);
	String sql ="SELECT * FROM article";
        Statement stmt;
        ResultSet rs;
        
       
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(sql);
       //      ArticleTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch(SQLException ex){
            Logger.getLogger(submitArticle.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArticleTable = new javax.swing.JTable();
        SubmitButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        titleCombo = new javax.swing.JComboBox<>();
        pathCombo = new javax.swing.JComboBox<>();
        pagesCombo = new javax.swing.JComboBox<>();
        summaryCombo = new javax.swing.JComboBox<>();
        keyWordsCombo = new javax.swing.JComboBox<>();
        categoryCombo = new javax.swing.JComboBox<>();
        pageNumCombo = new javax.swing.JComboBox<>();
        authorCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please enter the compartments of the article you want to submit :");

        ArticleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ArticleTable);

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("path:");

        jLabel3.setText("Title:");

        jLabel4.setText("Page:");

        jLabel6.setText("Summary:");

        jLabel7.setText("Key Words:");

        jLabel8.setText("Category ID:");

        jLabel9.setText("Page Number:");

        jLabel10.setText("Author:");

        titleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleComboActionPerformed(evt);
            }
        });

        categoryCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(titleCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE)
                                            .addComponent(pathCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pagesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(SubmitButton)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ExitButton)
                                        .addComponent(jLabel9))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(summaryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(keyWordsCombo, 0, 99, Short.MAX_VALUE)
                            .addComponent(categoryCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pageNumCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(pathCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyWordsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(titleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pagesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(pageNumCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(summaryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(authorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(ExitButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FillTable()
    {
	try{
	    Connection con = DriverManager.getConnection(url);
	    String sql ="SELECT * FROM article";
	    //PreparedStatement pst = con.prepareStatement(sql);
	    //ResultSet rs = pst.executeQuery();
	    Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
	    ResultSet rs = stmt.executeQuery(sql);
	    //ArticleTable.setModel(DbUtils.resultSetToTableModel(rs));
	    
	    
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }    
    
    private void FillComboPath()
    {
	try
	{
	    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	    //String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SELECT article_path FROM article";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("article_path");
		pathCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  
    
    private void FillComboTitle()
    {
	try
	{
	    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	    //String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SELECT title FROM article";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("title");
		titleCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  
    
    private void FillComboPages()
    {
	try
	{
	   // Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	   // String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SELECT pages FROM article";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("pages");
		pagesCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  
    
    private void FillComboSummary()
    {
	try
	{
	   // Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	   // String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SELECT summary FROM article";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("summary");
		summaryCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  
    
private void FillComboAuthor()
    {
	try
	{
	   // Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	   // String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SELECT journalist_email FROM journalist";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("journalist_email");
		authorCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  
   
    private void FillComboKeyWords()
    {
	try
	{
	  //  Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	  //  String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SELECT key_word FROM article";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("key_word");
		keyWordsCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  
    
    private void FillComboCategory()
    {
	try
	{
	    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	    //String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SELECT category_id FROM article";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("category_id");
		categoryCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  
    
    private void FillComboPageNum()
    {
	try
	{
	    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");       
	    //String url ="jdbc:sqlserver://projectapp.database.windows.net:1433;databaseName=dlab1;user=admin1@projectapp;password=EvaeisaiGTP*;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
	    Connection con = DriverManager.getConnection(url);
	    String sql = "SELECT page_number FROM article";
	    PreparedStatement pst = con.prepareStatement(sql);
	    ResultSet rs = pst.executeQuery();
	    while(rs.next())
	    {
		String name = rs.getString("page_number");
		pageNumCombo.addItem(name);		
	    }	
	}
	catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }  
    
    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        
           try {
               String connectionUrl =
                "jdbc:sqlserver://projectapp.database.windows.net:1433;"
                + "database=dlab1;"
                + "user=admin1@projectapp;"
                + "password=EvaeisaiGTP*;"
                + "encrypt=true;"
                + "trustServerCertificate=false;"
                + "loginTimeout=30;";
               
       Connection c = DriverManager.getConnection(connectionUrl);;
       Statement statement = c.createStatement();
   //    statement.executeUpdate(query);
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.hide();
        Journalist newframe = new Journalist();
        newframe.setVisible(true);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void titleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleComboActionPerformed

    private void categoryComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboActionPerformed

    /**
     * @param args the command line arguments
     */                
    public static void main(String args[])
    {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try
	{
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
	    {
		if ("Nimbus".equals(info.getName()))
		{
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex)
	{
	    java.util.logging.Logger.getLogger(submitArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex)
	{
	    java.util.logging.Logger.getLogger(submitArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex)
	{
	    java.util.logging.Logger.getLogger(submitArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex)
	{
	    java.util.logging.Logger.getLogger(submitArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */            
	java.awt.EventQueue.invokeLater(new Runnable()
	{
	    public void run()
	    {
		new submitArticle().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ArticleTable;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JComboBox<String> authorCombo;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> keyWordsCombo;
    private javax.swing.JComboBox<String> pageNumCombo;
    private javax.swing.JComboBox<String> pagesCombo;
    private javax.swing.JComboBox<String> pathCombo;
    private javax.swing.JComboBox<String> summaryCombo;
    private javax.swing.JComboBox<String> titleCombo;
    // End of variables declaration//GEN-END:variables
}